title: "Digital Rendering Engineering"
description: "Advanced Mathematics & Physics for Graphics Programmers"
baseurl: "/blog"
url: "https://opticsoptimization.github.io"
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed

kofi_username: "opticsoptimization"
kofi_url: "https://ko-fi.com/opticsoptimization"
